//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangChamCong
    {
        public int MaCong { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.DateTime> NgayLam { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public string AnhMinhChung { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
